apiVersion: v1
kind: Service
metadata:
  name: jobseer-service
  namespace: jobseer
spec:
  type: NodePort
  selector:
    app: jobseer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
